name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download 1password
      run: |
        mkdir -p .bin
        echo `realpath .bin` >> $GITHUB_PATH
        (cd .bin && (wget -qO- https://cache.agilebits.com/dist/1P/op/pkg/v1.8.0/op_linux_amd64_v1.8.0.zip | jar xv) && chmod +x op)

    - name: Verify 1password is executable
      run: op -v

    - name: Build with Gradle
      run: ./gradlew build
