name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ONE_PASSWORD_VERSION: 1.8.0

jobs:
  linux:
    name: Compile & Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      max-parallel: 1 # tests are not safe to be executed in parallel

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build
      env:
        OP_TEST_SIGNINADDRESS: ${{ secrets.OP_TEST_SIGNINADDRESS }}
        OP_TEST_EMAILADDRESS: ${{ secrets.OP_TEST_EMAILADDRESS }}
        OP_TEST_SECRETKEY: ${{ secrets.OP_TEST_SECRETKEY }}
        OP_TEST_PASSWORD: ${{ secrets.OP_TEST_PASSWORD }}
        OP_TEST_DEVICE: ${{ secrets.OP_TEST_DEVICE }}
        OP_TEST_EMAILADDRESS_TEMPLATE_PREFIX: ${{ secrets.OP_TEST_EMAILADDRESS_TEMPLATE_PREFIX }}
        OP_TEST_EMAILADDRESS_TEMPLATE_SUFFIX: ${{ secrets.OP_TEST_EMAILADDRESS_TEMPLATE_SUFFIX }}

    - name: Teamscale Upload
      if: ${{ always() }}
      env:
        PATH: ${{ github.workspace }}/build/bin
      run: |
        teamscale-upload --server https://teamscale.io --project GitHub-mpdeimos-onepassword-java --user mpdeimos --accesskey ${{ secrets.TEAMSCALE_ACCESS_KEY }} --partition "Test ${{ runner.os }}" --input teamscale-upload.config