name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ONE_PASSWORD_VERSION: 1.8.0

jobs:
  linux:
    name: Compile & Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      max-parallel: 1 # tests are not safe to be executed in parallel

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build
      env:
        OP_TEST_SIGNINADDRESS: ${{ secrets.OP_TEST_SIGNINADDRESS }}
        OP_TEST_EMAILADDRESS: ${{ secrets.OP_TEST_EMAILADDRESS }}
        OP_TEST_SECRETKEY: ${{ secrets.OP_TEST_SECRETKEY }}
        OP_TEST_PASSWORD: ${{ secrets.OP_TEST_PASSWORD }}
        OP_TEST_DEVICE: ${{ secrets.OP_TEST_DEVICE }}

    - name: Teamscale Upload
      if: ${{ always() && runner.os == 'Linux' }}
      env:
        TEAMSCALE_ACCESS_KEY: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
      run: |
        chmod +x ./build/bin/teamscale-upload
        ./build/bin/teamscale-upload --server https://teamscale.io --project GitHub-mpdeimos-onepassword-java --user mpdeimos --accesskey $TEAMSCALE_ACCESS_KEY --partition "test" --input teamscale-upload.config